/**
 * Copy — English only
 * For accurate geometric structure, language must be singular.
 */
export const copy = {
  title: 'Planetary Hello World',
  subtitle: 'Ø Super Singularity Genesis',
  axiom: 'Axiom',
  theorem: 'Theorem',
  axiomaticSystem: 'Axiomatic System',
  spirit: 'Spirit',
  body: 'Body',
  axiomaticity: 'Axiomaticity',
  eventHorizon: 'Event Horizon',
  pureAxiomaticity: 'Pure Axiomaticity',
  states: {
    exists: 'x exists (x=1)',
    notExists: 'x does not exist (x=0)',
    both: 'x exists and does not exist (x=1 ∩ x=0)',
    neither: 'x is neither "existing and non-existing" ¬(x=1 ∩ x=0)',
  },
  zfcInside: 'x>0 (inside ZFC)',
  zfcOutside: 'x<0 (outside ZFC)',
  boundary: 'Boundary',
  archivesOfAxiom: 'Archives of Axiom',
  calibration: {
    space: 'Space',
    spaceDesc: 'Thurston geometrization · Perelman proof',
    galaxy: 'Galaxy',
    galaxyDesc: 'Laniakea Supercluster',
    solar: 'Solar',
    solarDesc: 'Solar system calibration',
    planet: 'Planet',
    planetDesc: 'Planetary calibration',
    civil: 'Civil',
    civilDesc: 'ISO year month day hour minute second',
    orbit: 'Orbit',
    timeOrbit: 'Time/Orbit Calibration',
    cosmicEvent: 'Cosmic Event',
    cosmicEventDesc: 'Big Bang prediction models',
    timeOrbitDesc: 'Earth orbital position',
  },
  matterVerse: 'MatterVerse',
  matterVerseDesc:
    'Premise axioms, location, time for an Entity gliding through all possible space landing on this Planet under ZFC boundary conditions',
  aboutPhw: 'About PHW',
  top: 'Top',
  architect: 'Architect',
  architectDesc: 'Design Specification',
  journeyMap: 'Journey',
  genesisTrigger: 'Genesis Trigger',
  tutorials: 'Tutorials',
  tutorialStartupSequence: 'Startup Sequence',
  tutorialRecommendedTraining: 'Recommended Training',
  tutorialErrorHandling: 'Error Handling',
  events: 'Events',
  eventsSchedule: 'Events Schedule',
  scheduleArchive: 'Schedule Archive',
  calibrators: 'Calibrators',
  calibratorsCoordinates: 'Coordinates',
} as const
